// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: ".env.local" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL (non-pooled, port 5432) is used for migrations to bypass PgBouncer.
    // DATABASE_URL (pooler, port 6543) is used at runtime via PrismaPg adapter in lib/db.ts.
    // If DIRECT_URL is not set (e.g. local dev without pooler), falls back to DATABASE_URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
